# Ubuntu testing container
# Usually tagged as ghcr.io/notgull/keter:ubuntu

FROM rust as final
ARG DEBIAN_FRONTEND=noninteractive

RUN \
apt-get -o Acquire::Retries=10 -qq update && \
apt-get -o Acquire::Retries=10 -o Dpkg::Use-Pty=0 install -y --no-install-recommends \
    xvfb \
    libx11-dev \
    libxcb1-dev \
    libxkbcommon-dev && \
rm -rf \
    /var/lib/apt/lists/* \
    /var/cache/* \
    /var/log/* \
    /usr/share/{doc,man}
